import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react';
import Characters from './src/components/Characters';

export default function Home() {
  const [characters, setCharacters] = useState(null);

  const reqApi = async () => {
    const api= await fetch('https://rickandmortyapi.com/api/character')
    const characterApi = await api.json()
    console.log(characterApi);
    setCharacters(characterApi.results)
  };


  return (
    <>
      <Head>
        <title>Ricky&MOrty</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="App">
        <header className="App-header">
          <h1 className="title">
            Rick & Morty
          </h1>
          {characters ? (
            <Characters characters={characters} setCharacters={setCharacters}/>
          ) : (
            <>
            <Image src="/img/rick-mortyh.png" alt="Rick & Morty" width={300} height={300} />
            <button onClick={reqApi} className="btn-search">Buscar personajes</button>
            </>
          )}
          
          
        </header>
      </div>
    </>
  )
}
